version: '3'
services:
  api:
    build: ./build/develop/go/ # ビルドに使うDockerfileの場所
    tty: true # コンテナ永続化の設定
    volumes:
      - ./api:/go/src/api # マウントディレクトリ
    ports:
      - '8080:8080'
    #    env_file:
      #  - mysql_and_datetime.env
